### ISSUE TITLE
i19.screen is too slow

### ISSUE THREAD

**Issue by Anthchirp** [xia2/i19#1]
Users at I19 commented that a lot of their time is now spent not collecting data, but waiting on the output of i19.screen as a significant rate-limiting step.

Suggestions are:
- create datablock.json in data collection python script
- automatically run i19.screen after data collection
- improve the runtimes of various dials steps

**Comment by graeme-winter** [comment]
#1 should probably be considered a general Diamond challenge => MX as well
as I19; #2 is certainly an inhouse issue but trivial to resolve

#3 [citation needed] please provide profile information :o)

**Comment by Anthchirp** [comment]
#1 tracked in http://jira.diamond.ac.uk/browse/MXGDA-2645

**Comment by Anthchirp** [comment]
i19.screen can now "quick import" single sweeps (derive full datablock.json from first image) and runs automatically after data collection. Further improvements are planned regarding processing during the data collection, but this is beyond the scope of this ticket.
